name: beam-me-up
version: "1.1.1-SNAPSHOT"
description: "A SpigotMC plugin that is used to teleport players between predefined locations!"
author: Carbon
api-version: "1.14"
main: me.carbon.plugins.beammeup.BeamMeUp

commands:
  beam:
    description: "Main command for the beam-me-up plugin"
    usage: |
      /beam go <location> - teleports the player to a saved location with the name <location>
      /beam set <location> - takes the location the player is currently at and saves it as <location>
      /beam list - lists all the names of saved locations
      /beam remove <location> - removes a location from the list of saved locations

permissions:
  beam.*:
    description: Permission to allow all sub-commands
    default: op
    children:
      beam.go: true
      beam.set: true
      beam.list: true
      beam.remove: true

  beam.go:
    description: Permission to allow the go sub-command
    default: true

  beam.set:
    description: Permission to allow the set sub-command
    default: false

  beam.list:
    description: Permission to allow the list sub-command
    default: true

  beam.remove:
    description: Permission to allow the remove sub-command
    default: false
