name: beam-me-up
main: me.carbon.plugins.beammeup.BeamMeUp
version: "1.0.2"
api-version: "1.14"
author: Carbon
description: "A SpigotMC plugin that is used to teleport players between predefined locations!"

commands:
  beam:
    description: "Main command for the beam-me-up plugin"
    usage: /beam [go, set] <args>