name: beam-me-up
version: 2.0.0-SNAPSHOT
description: A SpigotMC plugin that is used to teleport players between predefined/saved locations!
author: Carbon
api-version: "1.14"
main: me.carbon.plugins.beammeup.BeamMeUp

commands:
  beam:
    description: Root command for the beam-me-up plugin
    permission: beam.command
    usage: |
      /beam go <location>
      /beam set <location>
      /beam list
      /beam remove <location>
      /beam rename <location> <newName>

permissions:
  beam.command:
    description: Permission that allows usage of the base beam command
    default: op

  beam.*:
    description: Permission to allow all sub-commands
    default: op
    children:
      beam.go: true
      beam.set: true
      beam.list: true
      beam.remove: true
      beam.rename: true

  beam.go:
    description: Permission to allow the go sub-command
    default: true
    children:
      beam.command: true

  beam.set:
    description: Permission to allow the set sub-command
    default: false
    children:
      beam.command: true

  beam.list:
    description: Permission to allow the list sub-command
    default: true
    children:
      beam.command: true

  beam.remove:
    description: Permission to allow the remove sub-command
    default: false
    children:
      beam.command: true

  beam.rename:
    description: Permission to allow the rename sub-command
    default: false
    children:
      beam.command: true
